@startuml

package controller {
    class UsuarioController
    class CompeticaoController
    class ResultadoController
}

package service {
    class UsuarioService
    class CompeticaoService
    class ResultadoService
    class NotificacaoService
}

package repository {
    class UsuarioRepository
    class CompeticaoRepository
    class ResultadoRepository
}

package dto {
    class UsuarioDTO
    class CompeticaoDTO
    class ResultadoDTO
}

package mapper {
    class UsuarioMapper
    class CompeticaoMapper
    class ResultadoMapper
}

package exception {
    class AutenticacaoException
    class CompeticaoException
    class InscricaoException
}

package model {
    class Usuario
    class Atleta
    class Administrador

    class Competicao
    class Local
    class Inscricao

    class Resultado
    class Relatorio

    class Pais
}

package notification {
    class Notificacao
}

package security {
    class Autenticacao
}

package enums {
    enum StatusCompeticao
    enum StatusInscricao
    enum TipoMedalha
}

controller ..> service
controller ..> exception
controller ..> dto

service ..> repository
service ..> mapper
service ..> notification
service ..> exception

repository ..> model

mapper ..> dto
mapper ..> model

security ..> model
security ..> exception

@enduml